# Generated by Django 5.0.14 on 2026-08-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('cashier_id', models.UUIDField(blank=True, null=True)),
                ('cashier_name', models.CharField(blank=True, max_length=80)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opening_float_minor', models.BigIntegerField(default=0)),
                ('expected_cash_minor', models.BigIntegerField(default=0)),
                ('counted_cash_minor', models.BigIntegerField(default=0)),
                ('variance_minor', models.BigIntegerField(default=0)),
                ('variance_reason', models.CharField(blank=True, max_length=240)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='accounts.device')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('denomination_minor', models.BigIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=32)),
                ('count', models.PositiveIntegerField(default=0)),
                ('line_total_minor', models.BigIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='shifts.shift')),
            ],
            options={
                'ordering': ['-denomination_minor'],
            },
        ),
    ]
