# Generated by Django 5.0.14 on 2026-08-09 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('staff.created', 'Staff created'), ('staff.updated', 'Staff updated'), ('staff.deactivated', 'Staff deactivated'), ('staff.reactivated', 'Staff reactivated')], db_index=True, max_length=32)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('actor_name', models.CharField(blank=True, max_length=120)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
            ],
            options={
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['branch', '-id'], name='audit_audit_branch__1e24c5_idx')],
            },
        ),
    ]
