# Generated by Django 5.0.14 on 2026-08-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('staff.created', 'Staff created'), ('staff.updated', 'Staff updated'), ('staff.deactivated', 'Staff deactivated'), ('staff.reactivated', 'Staff reactivated'), ('item.created', 'Menu item created'), ('item.updated', 'Menu item updated'), ('item.retired', 'Menu item retired'), ('item.image', 'Menu item photo changed'), ('category.created', 'Category created'), ('category.updated', 'Category updated'), ('category.deactivated', 'Category deactivated'), ('price.bulk', 'Bulk price change'), ('delivery.status', 'Delivery status changed'), ('customer.created', 'Customer created'), ('customer.updated', 'Customer updated'), ('customer.retired', 'Customer retired'), ('customer.settled', 'Customer settled a debt'), ('profile.branding', 'Landing page branding changed')], db_index=True, max_length=32),
        ),
    ]
