# Generated by Django 5.0.14 on 2026-08-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(db_index=True, max_length=32)),
                ('type', models.CharField(choices=[('dine_in', 'Dine in'), ('takeaway', 'Takeaway'), ('delivery', 'Delivery')], default='dine_in', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('parked', 'Parked'), ('sent', 'Sent to kitchen'), ('closed', 'Closed'), ('void', 'Void')], db_index=True, default='open', max_length=16)),
                ('table_id', models.UUIDField(blank=True, null=True)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('subtotal_minor', models.BigIntegerField(default=0)),
                ('discount_minor', models.BigIntegerField(default=0)),
                ('total_minor', models.BigIntegerField(default=0)),
                ('opened_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier_id', models.UUIDField(blank=True, null=True)),
                ('cashier_name', models.CharField(blank=True, max_length=80)),
                ('shift_ref', models.UUIDField(blank=True, db_index=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=240)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('corrects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='orders.order')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.device')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shifts.shift')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('item_id', models.UUIDField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('unit_price_minor', models.BigIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('modifiers_text', models.CharField(blank=True, max_length=240)),
                ('line_total_minor', models.BigIntegerField()),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.CharField(blank=True, max_length=240)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('wallet', 'E-wallet'), ('credit', 'Credit (آجل)')], max_length=16)),
                ('amount_minor', models.BigIntegerField()),
                ('tendered_minor', models.BigIntegerField(blank=True, null=True)),
                ('change_minor', models.BigIntegerField(default=0)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('customer_id', models.UUIDField(blank=True, null=True)),
                ('taken_at', models.DateTimeField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['taken_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['branch', 'status'], name='orders_orde_branch__e95c01_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shift', 'status'], name='orders_orde_shift_i_22a392_idx'),
        ),
    ]
