# Generated by Django 5.0.14 on 2026-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kitchen_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='kitchen_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
