# Generated by Django 5.0.14 on 2026-10-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_channel_order_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberCounter',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.BigIntegerField(default=1000)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='client_request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
