# Generated by Django 5.2.17 on 2026-10-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_online_order_idempotency_and_number_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('ready_for_pickup', 'Ready for pickup'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], db_index=True, max_length=20),
        ),
    ]
