# Generated by Django 5.0.14 on 2026-08-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['sort', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('description_ar', models.CharField(blank=True, max_length=240)),
                ('description_en', models.CharField(blank=True, max_length=240)),
                ('price_minor', models.BigIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category')),
            ],
            options={
                'ordering': ['sort', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('old_price_minor', models.BigIntegerField()),
                ('new_price_minor', models.BigIntegerField()),
                ('reason', models.CharField(choices=[('manual', 'Manual edit'), ('bulk_percent', 'Bulk percentage change'), ('sync', 'Applied from server')], default='manual', max_length=16)),
                ('percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('applied_at', models.DateTimeField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_changes', to='catalog.menuitem')),
                ('source_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.device')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_active'], name='catalog_men_categor_127d25_idx'),
        ),
    ]
