# Generated by Django 5.0.14 on 2026-08-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu-items/'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
