# Generated by Django 5.2.17 on 2026-10-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_manageruser_session_version'),
        ('catalog', '0002_menuitem_image_menuitem_is_featured'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityChange',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField()),
                ('changed_at', models.DateTimeField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_changes', to='catalog.menuitem')),
                ('source_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.device')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
