# Generated by Django 5.0.14 on 2026-08-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSettlement',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('amount_minor', models.BigIntegerField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('wallet', 'E-wallet')], default='cash', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('taken_at', models.DateTimeField()),
                ('received_by_name', models.CharField(blank=True, max_length=80)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='customers.customer')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch', 'is_active'], name='customers_c_branch__e67b0c_idx'),
        ),
    ]
