# Generated by Django 5.0.14 on 2026-08-06 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantProfile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField()),
                ('server_created_at', models.DateTimeField(auto_now_add=True)),
                ('server_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name_ar', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('description_ar', models.CharField(blank=True, max_length=300)),
                ('description_en', models.CharField(blank=True, max_length=300)),
                ('address_ar', models.CharField(blank=True, max_length=240)),
                ('address_en', models.CharField(blank=True, max_length=240)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('whatsapp', models.CharField(blank=True, max_length=32)),
                ('map_url', models.URLField(blank=True)),
                ('hours', models.JSONField(blank=True, default=list)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('delivery_links', models.JSONField(blank=True, default=list)),
                ('landing_page_enabled', models.BooleanField(default=False)),
                ('prices_updated_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.branch')),
            ],
            options={
                'ordering': ['name_ar'],
            },
        ),
    ]
