# Generated by Django 5.0.14 on 2026-08-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
