# Generated by Django 5.0.14 on 2026-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_restaurantprofile_hero_image_restaurantprofile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='online_ordering_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
