# Generated by Django 5.0.14 on 2026-08-08 16:18

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='manageruser',
            managers=[
                ('objects', apps.accounts.models.ManagerUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='manageruser',
            name='display_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='manageruser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('kitchen', 'Kitchen')], default='manager', max_length=16),
        ),
    ]
