# Generated by Django 5.0.14 on 2026-10-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_manageruser_managers_manageruser_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manageruser',
            name='session_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
